version: '3.8'

services:
  mongodb:
    image: mongo:4.4.18
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminPassword
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      
  init_and_seed_db:
    build: .  
    environment:
      - MONGODB_URI=mongodb://admin:adminPassword@mongodb:27017/petFeederDB
    depends_on:
      - mongodb

  petfeederapi:
    image: petfeederapi:latest
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://admin:adminPassword@mongodb:27017/petFeederDB
    depends_on:
      - mongodb

volumes:
  mongodb_data: